### ISSUE TITLE
includes (met HTML)

### ISSUE THREAD

**Issue by fruitl00p** [Saabbass/presetSignUp#1]
Kleine "tip van Jip" als je een footer (of header) include in een ander bestand: let er dan op dat die include niet opnieuw een volledig html-bestand is maar puur de 'uitgeknipte' stukken uit de header- en footer code van het origineel:

`index.php`
```
<html>
<head>
<title>Hier is de titel</title>
</head>
<body>
<section id="header"></section>
<section id="content"></section>
<section id="footer"></section>
</body>
</html>
```
Wordt dan:
`index.php`
```
<html>
<head>
<title>Hier is de titel</title>
</head>
<body>
<?php include 'header.php'; ?>
<section id="content"></section>
<?php include 'footer.php'; ?>
</body>
</html>
```
`header.php`
```
<section id="header"></section>
````
`footer.php`
```
<section id="footer"></section>
```

Anders krijg je allemaal extra (invalide) html eruit ...

**Comment by Saabbass** [comment]
Top bedankt! 
Ik heb het nadat je het aangegeven had al snel aangepast. 
Was vergeten de issue te sluiten. 
Nogmaals bedankt!!
